services:
  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8080:8080"

  app:
    build: ./app
    container_name: app
    depends_on:
      - clearml
    ports:
      - "8000:8000"
    environment:
      # Replace these with your actual credentials and keys
      HUGGINGFACE_HUB_TOKEN: "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"
      CLEARML_API_ACCESS_KEY: "W490RUNUI01X1UYZ728NYMPTZQM8P2"
      CLEARML_API_SECRET_KEY: "iIcU4ZJGw_1LG5B8DR6grEGIY-9Vu-anLPapMssHITjaDxGEyfrZQq6tfsQ1BcVU0oE"
      CLEARML_API_SERVER: "http://clearml:8080"

      # MongoDB URI for your cloud instance
      MONGODB_URI: "mongodb+srv://and8995:Aniks777@cluster0.4voet.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

      # Qdrant Cloud Credentials and URL
      QDRANT_HOST: "https://fc94b6ab-f5e6-4b45-8e7c-51ed48367a37.us-east4-0.gcp.cloud.qdrant.io"
      QDRANT_PORT: "6333"
      QDRANT_API_KEY: "rzwHZa71bmoNZzJ2YlEvuwWoH8-2WifxSLywPqZc-o8zkaKilb3z1w"
    volumes:
      - ./:/app